#!/usr/bin/env ruby
# Build _data/github_projects.yml from repos.json (used by .github/workflows/sync-repos.yml)
# Run from repo root after Fetch public repos step has created repos.json.

require "json"
require "yaml"

repos = JSON.load(File.read("repos.json"))
out = {
  "repositories" => repos.map do |r|
    {
      "name" => r["name"],
      "description" => (r["description"] || "").to_s,
      "html_url" => r["html_url"],
      "stargazers_count" => r["stargazers_count"],
      "forks_count" => r["forks_count"],
      "updated_at" => r["updated_at"],
      "language" => (r["language"] || "").to_s,
    }
  end,
}
header = "# Auto-generated by .github/workflows/sync-repos.yml\n"
header += "# Last updated: #{Time.now.utc.strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
File.write("_data/github_projects.yml", header + out.to_yaml)
